# Example only - do not store real credentials in Git
apiVersion: v1
kind: Secret

metadata:
  name: mongodb-keyfile-secret
  namespace: hotel-project

type: Opaque

stringData:
  mongodb-keyfile: YOUR_MONGODB_KEYFILE
