apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
  namespace: hotel-project

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: adibush/hotel-backend:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 5000
