apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
  namespace: hotel-project

spec:
  replicas: 5

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: adibush/hotel-backend:bd10b0433eab673af3ea969e62eed2b59333439c

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGO_HOST

            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGO_PORT

            - name: MONGO_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGO_HOSTS

            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DATABASE_NAME

            - name: MONGO_REPLICA_SET
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGO_REPLICA_SET

            - name: MONGO_AUTH_SOURCE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGO_AUTH_SOURCE

            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME

            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
