apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment
  namespace: hotel-project

spec:
  replicas: 5

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend

          image: adibush/hotel-frontend:47ab1fbdefa26c14384dde034b7e23a84a1c9476

          imagePullPolicy: Always

          ports:
            - containerPort: 80
