apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment
  namespace: hotel-project

spec:
  replicas: 5

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend

          image: adibush/hotel-frontend:e58e835a6ec7557ff0ccb5ba1fe5a03463bb2020

          imagePullPolicy: Always

          ports:
            - containerPort: 80
