apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment
  namespace: hotel-project

spec:
  replicas: 5

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend

          image: adibush/hotel-frontend:fde7d6ef3cf1d897a5ce5d5a7014503e4617ed62

          imagePullPolicy: Always

          ports:
            - containerPort: 80
